import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('user@test.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Password' }).fill('password123');
  await page.getByRole('button', { name: 'Login' }).click();


  // Again, this is generated by the playwright codegen too and the logic inside has to be written manually.
  page.once('dialog', dialog => {
    // The confirmaion dialog appeared and we confirm him
    dialog.accept().catch(() => {
      
    });
  });
  await page.getByRole('button', { name: 'Delete' }).click();
  await expect(page.getByText('Review related papersMediumSummarize 5 papers and compare methodology sections.')).not.toBeVisible();

  // Manual step
  await expect(await page.getByText('Task deleted successfully', { exact: true })).toBeVisible();
}); 